// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xmedicalehr.api.Data;

namespace xmedical_ehr.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("xmedicalehr.api.Account.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "985b99c6-92bb-4dc0-b77d-ac3d49ade911",
                            ConcurrencyStamp = "46e95c99-7758-45c9-8a45-77403801d072",
                            DisplayName = "Administrador",
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Prefix")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasColumnName("varchar(45)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "ce93a609-02a9-4e24-8862-efeaabd9c397",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9b82e89-edd5-48a0-a728-7e92c90fb921",
                            Email = "root@system.local",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Root",
                            NormalizedEmail = "ROOT@SYSTEM.LOCAL",
                            NormalizedUserName = "ROOT@SYSTEM.LOCAL",
                            PasswordHash = "AQAAAAEAACcQAAAAEBEI92DDQ3rQr8oCpJKHlvz1hN/VDJpzGkFdV3qEHSjAQdLm5q6JEvzmS6sJpQnHMw==",
                            PhoneNumberConfirmed = false,
                            Prefix = "Sr",
                            SecurityStamp = "6XKETTFVMB3X6M4ENBW6YYVZYCTO52XW",
                            TwoFactorEnabled = false,
                            UserName = "root@system.local"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AlergiaPaciente", b =>
                {
                    b.Property<string>("PacienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SustanciaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comentario")
                        .HasColumnType("varchar(200)");

                    b.HasKey("PacienteId", "SustanciaId")
                        .HasName("PRIMARY");

                    b.HasIndex("SustanciaId");

                    b.ToTable("AlergiasPacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AntecedentePaciente", b =>
                {
                    b.Property<string>("PacienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoAntecedenteId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Deleted")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("PacienteId", "TipoAntecedenteId")
                        .HasName("PRIMARY");

                    b.HasIndex("TipoAntecedenteId");

                    b.ToTable("AntecedetesPacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Aseguradora", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoInt")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Aseguradoras");

                    b.HasData(
                        new
                        {
                            Id = "ebe7bd32-5f59-45d6-8665-60e0a23907a4",
                            Nombre = "SENASA"
                        },
                        new
                        {
                            Id = "20c12530-3e6a-4382-81c1-08504ff7a7c5",
                            Nombre = "ARS HUMANO"
                        },
                        new
                        {
                            Id = "ba0767a0-5dd8-4d22-adfd-f95fbe334d6a",
                            Nombre = "UNIVERSAL"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AtencionMedica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AseguradoraId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CamaId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Deleted")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EdadPaciente")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("FirmaPaciente")
                        .HasColumnType("varbinary(2048)");

                    b.Property<string>("MedicoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreFinanciador")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Origen")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PacienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoFinanciamiento")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoId")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("AseguradoraId");

                    b.HasIndex("CamaId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TipoId");

                    b.ToTable("AtencionesMedicas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Cama", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HabitacionId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Camas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Departamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Diagnostico", b =>
                {
                    b.Property<string>("NotaMedicaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumItem")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comentario")
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EnfermedadId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("NotaMedicaId", "NumItem")
                        .HasName("PRIMARY");

                    b.HasIndex("EnfermedadId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Eslogan")
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(2038)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Enfermedad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Catalogo")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Keywords")
                        .HasColumnType("varchar(2045)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Enfermedades");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Estudio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Estudios");

                    b.HasData(
                        new
                        {
                            Id = "b4f83c55-ccab-4b42-a390-b53bf89c041b",
                            Descripcion = "HEMOGRAMA",
                            Tipo = "LAB"
                        },
                        new
                        {
                            Id = "aa4112d8-7873-493d-b7ad-8195fac3cc8e",
                            Descripcion = "ORINA",
                            Tipo = "LAB"
                        },
                        new
                        {
                            Id = "365fe1a5-e38f-4ca0-b961-e87a42fae0f4",
                            Descripcion = "COPROLOGICO",
                            Tipo = "LAB"
                        },
                        new
                        {
                            Id = "e713a94d-23cd-488b-a049-b7502ecf728c",
                            Descripcion = "SONOGRAFIA",
                            Tipo = "IMG"
                        },
                        new
                        {
                            Id = "6ee7a2a4-f377-4cb8-8c26-72995d7c92dd",
                            Descripcion = "TOMOGRAFIA",
                            Tipo = "IMG"
                        },
                        new
                        {
                            Id = "d5e758f5-e0bb-4a86-a8dd-db6375d1b334",
                            Descripcion = "RADIOGRAFIA",
                            Tipo = "IMG"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.ExploracionItem", b =>
                {
                    b.Property<string>("NotaMedicaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExploracionItemTemplateId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(255)");

                    b.HasKey("NotaMedicaId", "ExploracionItemTemplateId")
                        .HasName("PRIMARY");

                    b.HasIndex("ExploracionItemTemplateId");

                    b.ToTable("ExploracionItems");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.ExploracionItemTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Deleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ExploracionItemTemplates");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.GrupoAntecedente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("GruposAntecedentes");

                    b.HasData(
                        new
                        {
                            Id = "bf38a802-329f-4fc0-bba2-a67e02968ee5",
                            Descripcion = "PATOLOGICOS"
                        },
                        new
                        {
                            Id = "0a7eaf07-34ae-46ac-b70b-b5319683a004",
                            Descripcion = "NO PATOLOGICOS"
                        },
                        new
                        {
                            Id = "05cf3870-1f0d-400e-9cc0-8e77dd3b355b",
                            Descripcion = "PSIQUIATRICOS"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Habitacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = "910102a7-2fc8-4e7a-a1ac-148cf34ad315",
                            Descripcion = "Habitacion 301"
                        },
                        new
                        {
                            Id = "02bdb663-dc1c-4533-a86e-b6efa90a53e4",
                            Descripcion = "Habitacion 302"
                        },
                        new
                        {
                            Id = "e2633de8-5dd5-4489-8484-d1b6f982685e",
                            Descripcion = "Habitacion 303"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Medicacion", b =>
                {
                    b.Property<string>("AtencionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NotaEnfermeriaId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumItem")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedicamentoId")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Unidad")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Via")
                        .HasColumnType("varchar(45)");

                    b.HasKey("AtencionId", "NotaEnfermeriaId", "NumItem")
                        .HasName("PRIMARY");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("NotaEnfermeriaId");

                    b.ToTable("Medicaciones");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Medicamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Medicamentos");

                    b.HasData(
                        new
                        {
                            Id = "4b254d5d-1e92-419b-9f00-e060073ed002",
                            CreatedAt = new DateTime(2021, 8, 10, 15, 55, 39, 415, DateTimeKind.Local).AddTicks(1260),
                            Deleted = false,
                            Descripcion = "ACETAMINOFEN"
                        },
                        new
                        {
                            Id = "c95744c1-bd41-4245-baee-ba995324a05d",
                            CreatedAt = new DateTime(2021, 8, 10, 15, 55, 39, 415, DateTimeKind.Local).AddTicks(8787),
                            Deleted = false,
                            Descripcion = "PARACETAMOL"
                        },
                        new
                        {
                            Id = "99e852d4-1c9d-4031-9b64-7c22dd3883bb",
                            CreatedAt = new DateTime(2021, 8, 10, 15, 55, 39, 415, DateTimeKind.Local).AddTicks(8824),
                            Deleted = false,
                            Descripcion = "SOLUCION SALINA MIXTA 1000ml"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Nacionalidad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoInt")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Nacionalidades");

                    b.HasData(
                        new
                        {
                            Id = "f9076ab2-8e8f-4abc-849c-c401c84fa7ce",
                            Descripcion = "Dominicana"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaEnfermeria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AtencionId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EnfermeraId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("HabitusExterior")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("mediumtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("AtencionId");

                    b.HasIndex("EnfermeraId");

                    b.ToTable("NotasEnfermeria");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaMedica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AtencionId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DeOrden")
                        .HasColumnType("tinyint(1)");

                    b.Property<sbyte>("Deleted")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dieta")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EscalaDolor")
                        .HasColumnType("int");

                    b.Property<int>("EscalaGlasgow")
                        .HasColumnType("int");

                    b.Property<string>("ExamenFisico")
                        .HasColumnType("mediumtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("HistoriaEnfermedad")
                        .HasColumnType("mediumtext");

                    b.Property<string>("MedicoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("mediumtext");

                    b.Property<string>("MotivoEgreso")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Nota")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("mediumtext");

                    b.Property<string>("OtrosParametros")
                        .HasColumnType("varchar(1024)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Pronostico")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SaturacionOxigeno")
                        .HasColumnType("int)");

                    b.Property<string>("TipoNotaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UnidadPeso")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("AtencionId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("TipoNotaId");

                    b.ToTable("NotasMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaMedicaCustomField", b =>
                {
                    b.Property<string>("NotaMedicaId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumItem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Valor")
                        .HasColumnType("mediumtext");

                    b.HasKey("NotaMedicaId", "NumItem")
                        .HasName("PRIMARY");

                    b.ToTable("NotaMedicaCustomFields");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.OrdenMedica", b =>
                {
                    b.Property<string>("NotaMedicaId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumItem")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantiad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Comentario")
                        .HasColumnType("mediumtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("Deleted")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstudioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Instruccciones")
                        .HasColumnType("mediumtext");

                    b.Property<int>("Intervalo")
                        .HasColumnType("int");

                    b.Property<string>("MedicamentoId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Monodosis")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumDiagnostico")
                        .HasColumnType("int");

                    b.Property<bool>("Suspendido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tiempo")
                        .HasColumnType("varchar(45)");

                    b.Property<int>("TiempoExpiracion")
                        .HasColumnType("int");

                    b.Property<string>("TipoId")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Unidad")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Via")
                        .HasColumnType("varchar(100)");

                    b.HasKey("NotaMedicaId", "NumItem");

                    b.HasIndex("EstudioId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("OrdenesMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Paciente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AseguradoraId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cedula")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Celular")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Estatura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("NSS")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NacionalidadId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombres")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nota")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("NumAsegurado")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProvinciaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnidadEstatura")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("AseguradoraId");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasDatabaseName("Cedula_UNIQUE");

                    b.HasIndex("NacionalidadId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.PacienteParentesco", b =>
                {
                    b.Property<string>("PacienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoParentescoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParentescoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comentario")
                        .HasColumnType("varchar(200)");

                    b.HasKey("PacienteId", "TipoParentescoId", "ParentescoId")
                        .HasName("PRIMARY");

                    b.HasIndex("ParentescoId");

                    b.HasIndex("TipoParentescoId");

                    b.ToTable("PacientesParentescos");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Provincia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoInt")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = "4729ab09-56c6-4006-ac97-f88d736238cf",
                            Nombre = "Duarte"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.SignosVitales", b =>
                {
                    b.Property<string>("AtencionId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumItem")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Diuresis")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<string>("NotaEnfermeriaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NotaMedicaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Origen")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("PresionDiastolica")
                        .HasColumnType("int");

                    b.Property<int>("PresionSistolica")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnidadTemperatura")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AtencionId", "NumItem")
                        .HasName("PRIMARY");

                    b.HasIndex("NotaEnfermeriaId");

                    b.HasIndex("NotaMedicaId");

                    b.ToTable("SignosVitales");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.SolicitudInterconsulta", b =>
                {
                    b.Property<string>("AtencionId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumItem")
                        .HasColumnType("int");

                    b.Property<bool>("Atendido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartamentoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedicoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedicoInterconsultadoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Motivo")
                        .HasColumnType("mediumtext");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("mediumtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AtencionId", "NumItem")
                        .HasName("PRIMARY");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("MedicoInterconsultadoId");

                    b.ToTable("SolicitudesInterconsultas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Sustancia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Sustancias");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoAntecedente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GrupoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("GrupoId");

                    b.ToTable("TiposAntecedentes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoAtencion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("TiposAtenciones");

                    b.HasData(
                        new
                        {
                            Id = "E",
                            Descripcion = "Emergencia"
                        },
                        new
                        {
                            Id = "H",
                            Descripcion = "Hospitalizacion"
                        },
                        new
                        {
                            Id = "A",
                            Descripcion = "Ambulatoria"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoNotaMedica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("TiposNotasMedicas");

                    b.HasData(
                        new
                        {
                            Id = "I",
                            Descripcion = "Ingreso"
                        },
                        new
                        {
                            Id = "E",
                            Descripcion = "Evolucion"
                        },
                        new
                        {
                            Id = "EG",
                            Descripcion = "Egreso"
                        });
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoParentesco", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("TiposParentescos");

                    b.HasData(
                        new
                        {
                            Id = "db4876da-47e9-403e-97eb-8322221b938d",
                            Descripcion = "Esposo/a"
                        },
                        new
                        {
                            Id = "4f685201-628d-4000-8c1c-69b7cfd809ce",
                            Descripcion = "Padre"
                        },
                        new
                        {
                            Id = "cc42c566-66f3-4639-a256-59f099dbee32",
                            Descripcion = "Madre"
                        },
                        new
                        {
                            Id = "421505e1-0910-4cda-85fd-d55479352d49",
                            Descripcion = "Hijo/a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("xmedicalehr.api.Account.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("xmedicalehr.api.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("xmedicalehr.api.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("xmedicalehr.api.Account.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("xmedicalehr.api.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AlergiaPaciente", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Paciente", "Paciente")
                        .WithMany("Alergias")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_AlergiaPaciente_Pacientea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.Sustancia", "Sustancia")
                        .WithMany("Alergias")
                        .HasForeignKey("SustanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Sustancia");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AntecedentePaciente", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Paciente", "Paciente")
                        .WithMany("Antecedentes")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_AntecedentePaciente_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.TipoAntecedente", "TipoAntecedente")
                        .WithMany("AntecedentesPacientes")
                        .HasForeignKey("TipoAntecedenteId")
                        .HasConstraintName("FK_AntecedentePaciente_TipoAntecedente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("TipoAntecedente");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AtencionMedica", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Aseguradora", "Aseguradora")
                        .WithMany("Atenciones")
                        .HasForeignKey("AseguradoraId")
                        .HasConstraintName("FK_AtencionesMedicas_Aseguradoras");

                    b.HasOne("xmedicalehr.api.Models.Cama", "Cama")
                        .WithMany("Atenciones")
                        .HasForeignKey("CamaId")
                        .HasConstraintName("FK_AtencionesMedicas_Camas");

                    b.HasOne("xmedicalehr.api.Account.User", "Creator")
                        .WithMany("AtencionesCreadas")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_AtencionesMedicas_Creator");

                    b.HasOne("xmedicalehr.api.Account.User", "Medico")
                        .WithMany("Atenciones")
                        .HasForeignKey("MedicoId")
                        .HasConstraintName("FK_AtencionesMedicas_Medicos");

                    b.HasOne("xmedicalehr.api.Models.Paciente", "Paciente")
                        .WithMany("Atenciones")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_AtencionesMedicas_Pacientes");

                    b.HasOne("xmedicalehr.api.Models.TipoAtencion", "TipoAtencion")
                        .WithMany("Atenciones")
                        .HasForeignKey("TipoId")
                        .HasConstraintName("FK_AtencionesMedicas_TipoAtenciones");

                    b.Navigation("Aseguradora");

                    b.Navigation("Cama");

                    b.Navigation("Creator");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("TipoAtencion");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Cama", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Habitacion", "Habitacion")
                        .WithMany("Camas")
                        .HasForeignKey("HabitacionId")
                        .HasConstraintName("FK_Cama_Habitacion");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Diagnostico", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Enfermedad", "Enfermedad")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("EnfermedadId")
                        .HasConstraintName("FK_Diagnosticos_Enfermerdad");

                    b.HasOne("xmedicalehr.api.Models.NotaMedica", "NotaMedica")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("NotaMedicaId")
                        .HasConstraintName("FK_Diagnosticos_NotasMedicas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermedad");

                    b.Navigation("NotaMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.ExploracionItem", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.ExploracionItemTemplate", "ExploracionItemTemplate")
                        .WithMany("ExploracionItems")
                        .HasForeignKey("ExploracionItemTemplateId")
                        .HasConstraintName("FK_ExploracionItem_ExploracionItemTemplate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.NotaMedica", "NotaMedica")
                        .WithMany("ExploracionItems")
                        .HasForeignKey("NotaMedicaId")
                        .HasConstraintName("FK_ExploracionItem_NotasMedicas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExploracionItemTemplate");

                    b.Navigation("NotaMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Medicacion", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.AtencionMedica", "AtencionMedica")
                        .WithMany("Medicaciones")
                        .HasForeignKey("AtencionId")
                        .HasConstraintName("FK_Medicacion_AtencionesMedicas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.Medicamento", "Medicamento")
                        .WithMany("Medicaciones")
                        .HasForeignKey("MedicamentoId")
                        .HasConstraintName("FK_Medicacion_Medicamentos");

                    b.HasOne("xmedicalehr.api.Models.NotaEnfermeria", "NotaEnfermeria")
                        .WithMany("Medicaciones")
                        .HasForeignKey("NotaEnfermeriaId")
                        .HasConstraintName("FK_Medicacion_NotasEnfemeria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtencionMedica");

                    b.Navigation("Medicamento");

                    b.Navigation("NotaEnfermeria");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaEnfermeria", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.AtencionMedica", "AtencionMedica")
                        .WithMany("NotasEnfermeria")
                        .HasForeignKey("AtencionId")
                        .HasConstraintName("FK_NotaEnfermeria_AtencionMedia");

                    b.HasOne("xmedicalehr.api.Account.User", "Enfermera")
                        .WithMany("NotasEnfermeria")
                        .HasForeignKey("EnfermeraId")
                        .HasConstraintName("FK_NotaEnfermeria_Enfermera");

                    b.Navigation("AtencionMedica");

                    b.Navigation("Enfermera");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaMedica", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.AtencionMedica", "AtencionMedica")
                        .WithMany("NotasMedicas")
                        .HasForeignKey("AtencionId")
                        .HasConstraintName("FK_NotasMedicas_AtencionesMedica");

                    b.HasOne("xmedicalehr.api.Account.User", "Medico")
                        .WithMany("NotasMedicas")
                        .HasForeignKey("MedicoId")
                        .HasConstraintName("FK_NotasMedicas_Medicos");

                    b.HasOne("xmedicalehr.api.Models.TipoNotaMedica", "TipoNota")
                        .WithMany("NotasMedicas")
                        .HasForeignKey("TipoNotaId")
                        .HasConstraintName("FK_NotasMedicas_TiposNota");

                    b.Navigation("AtencionMedica");

                    b.Navigation("Medico");

                    b.Navigation("TipoNota");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaMedicaCustomField", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.NotaMedica", "NotaMedica")
                        .WithMany("CustomFields")
                        .HasForeignKey("NotaMedicaId")
                        .HasConstraintName("FK_NotasMedicasCustomField_NotasMedica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.OrdenMedica", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Estudio", "Estudio")
                        .WithMany("OrdenesMedicas")
                        .HasForeignKey("EstudioId")
                        .HasConstraintName("FK_OrdenesMedica_Estudios");

                    b.HasOne("xmedicalehr.api.Models.Medicamento", "Medicamento")
                        .WithMany("OrdenesMedicas")
                        .HasForeignKey("MedicamentoId")
                        .HasConstraintName("FK_OrdenesMedica_Medicamentos");

                    b.HasOne("xmedicalehr.api.Models.NotaMedica", "NotaMedica")
                        .WithMany("OrdenesMedicas")
                        .HasForeignKey("NotaMedicaId")
                        .HasConstraintName("FK_OrdenesMedica_NotasMedica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudio");

                    b.Navigation("Medicamento");

                    b.Navigation("NotaMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Paciente", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Aseguradora", "Aseguradora")
                        .WithMany("Pacientes")
                        .HasForeignKey("AseguradoraId")
                        .HasConstraintName("FK_Pacientes_Aseguradoras");

                    b.HasOne("xmedicalehr.api.Models.Nacionalidad", "Nacionalidad")
                        .WithMany("Pacientes")
                        .HasForeignKey("NacionalidadId")
                        .HasConstraintName("FK_Pacientes_Nacionalidades");

                    b.HasOne("xmedicalehr.api.Models.Provincia", "Provincia")
                        .WithMany("Pacientes")
                        .HasForeignKey("ProvinciaId")
                        .HasConstraintName("FK_Pacientes_Provincias");

                    b.Navigation("Aseguradora");

                    b.Navigation("Nacionalidad");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.PacienteParentesco", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.Paciente", "Paciente")
                        .WithMany("PacienteParentescos")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_PacienteParentescos_Pacientes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.Paciente", "Parentesco")
                        .WithMany("ParentescosPaciente")
                        .HasForeignKey("ParentescoId")
                        .HasConstraintName("FK_ParentescosPaciente_Pacientes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.TipoParentesco", "TipoParentesco")
                        .WithMany("PacientesParentesco")
                        .HasForeignKey("TipoParentescoId")
                        .HasConstraintName("FK_PacientesParentesco_TiposParentesco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Parentesco");

                    b.Navigation("TipoParentesco");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.SignosVitales", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.AtencionMedica", "Atencion")
                        .WithMany("SignosVitales")
                        .HasForeignKey("AtencionId")
                        .HasConstraintName("FK_SignosVitales_Atenciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.NotaEnfermeria", "NotaEnfermeria")
                        .WithMany("SignosVitales")
                        .HasForeignKey("NotaEnfermeriaId")
                        .HasConstraintName("FK_SignosVitales_NotasEnfermeria");

                    b.HasOne("xmedicalehr.api.Models.NotaMedica", "NotaMedica")
                        .WithMany("SignosVitales")
                        .HasForeignKey("NotaMedicaId")
                        .HasConstraintName("FK_SignosVitales_NotasMedica");

                    b.Navigation("Atencion");

                    b.Navigation("NotaEnfermeria");

                    b.Navigation("NotaMedica");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.SolicitudInterconsulta", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.AtencionMedica", "Atencion")
                        .WithMany("SolicitudesInterconsultas")
                        .HasForeignKey("AtencionId")
                        .HasConstraintName("FK_SolicitudInterconsulta_AtencionMedica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xmedicalehr.api.Models.Departamento", "Departamento")
                        .WithMany("SolicitudesInterconsultas")
                        .HasForeignKey("DepartamentoId")
                        .HasConstraintName("FK_SolicitudInterconsulta_Departamento");

                    b.HasOne("xmedicalehr.api.Account.User", "Medico")
                        .WithMany("InterconsultasSolicitadas")
                        .HasForeignKey("MedicoId")
                        .HasConstraintName("FK_SolicitudInterconsulta_MedicoSolicitante");

                    b.HasOne("xmedicalehr.api.Account.User", "MedicoInterconsultado")
                        .WithMany("SolicitudesInterconsultas")
                        .HasForeignKey("MedicoInterconsultadoId")
                        .HasConstraintName("FK_SolicitudInterconsulta_MedicoInterconsultado");

                    b.Navigation("Atencion");

                    b.Navigation("Departamento");

                    b.Navigation("Medico");

                    b.Navigation("MedicoInterconsultado");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoAntecedente", b =>
                {
                    b.HasOne("xmedicalehr.api.Models.GrupoAntecedente", "Grupo")
                        .WithMany("TiposAntecedentes")
                        .HasForeignKey("GrupoId")
                        .HasConstraintName("FK_TipoAntecedente_GrupoAntecedente");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("xmedicalehr.api.Account.User", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("AtencionesCreadas");

                    b.Navigation("InterconsultasSolicitadas");

                    b.Navigation("NotasEnfermeria");

                    b.Navigation("NotasMedicas");

                    b.Navigation("SolicitudesInterconsultas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Aseguradora", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.AtencionMedica", b =>
                {
                    b.Navigation("Medicaciones");

                    b.Navigation("NotasEnfermeria");

                    b.Navigation("NotasMedicas");

                    b.Navigation("SignosVitales");

                    b.Navigation("SolicitudesInterconsultas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Cama", b =>
                {
                    b.Navigation("Atenciones");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Departamento", b =>
                {
                    b.Navigation("SolicitudesInterconsultas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Enfermedad", b =>
                {
                    b.Navigation("Diagnosticos");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Estudio", b =>
                {
                    b.Navigation("OrdenesMedicas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.ExploracionItemTemplate", b =>
                {
                    b.Navigation("ExploracionItems");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.GrupoAntecedente", b =>
                {
                    b.Navigation("TiposAntecedentes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Habitacion", b =>
                {
                    b.Navigation("Camas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Medicamento", b =>
                {
                    b.Navigation("Medicaciones");

                    b.Navigation("OrdenesMedicas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Nacionalidad", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaEnfermeria", b =>
                {
                    b.Navigation("Medicaciones");

                    b.Navigation("SignosVitales");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.NotaMedica", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("Diagnosticos");

                    b.Navigation("ExploracionItems");

                    b.Navigation("OrdenesMedicas");

                    b.Navigation("SignosVitales");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Paciente", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Antecedentes");

                    b.Navigation("Atenciones");

                    b.Navigation("PacienteParentescos");

                    b.Navigation("ParentescosPaciente");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Provincia", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.Sustancia", b =>
                {
                    b.Navigation("Alergias");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoAntecedente", b =>
                {
                    b.Navigation("AntecedentesPacientes");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoAtencion", b =>
                {
                    b.Navigation("Atenciones");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoNotaMedica", b =>
                {
                    b.Navigation("NotasMedicas");
                });

            modelBuilder.Entity("xmedicalehr.api.Models.TipoParentesco", b =>
                {
                    b.Navigation("PacientesParentesco");
                });
#pragma warning restore 612, 618
        }
    }
}
